green/loader.py, green/test/test_loader.py
This attribute is set by nose.tools for functions that shouldn't
be considered tests (usually because they're a base for a generated
test function).
This change enables nose_parameterized with green.
Fixes #39
=> loader: Don't add tests which have __test__ set to False

.travis.yml
This allows us to use the container based infrastructure, which is
much faster.
Fixes #54
=> Use sudo: false in travis.yml

g
- Quoting allows args with wildcards to pass through to green
successfully.
- See http://stackoverflow.com/questions/2761723 for details.
=> Quote $@ in the g script

green/output.py, green/result.py, green/test/test_result.py
If stdout is connected to a pipe or file, this will result in
duplicate lines.
Check to make sure we're connected to a terminal first before
printing \r and other "status" like lines.
Fixes #52
=> Don't print \r if we're not connected to a terminal.

green/__main__.py
Add `__main__.py` to support alternative usage: `python -m green` - issue #91
=> enable "python -m green" - #91

appveyor.yml, cli-options.txt, green/config.py, green/result.py, green/test/test_result.py
I am testing a Flask application which is very verbose, and I only need the added output if the test fail. So this option should only display stdout/stderr if the test is not successful.
I am not sure about the best way to integrate this with your current tests can you help me on that ? Thanks !
=> Add --quiet-stdout option

.travis.yml, Makefile, setup.cfg
Records existing errors per file, for many common
flake8 plugins, preventing new flake8 errors.
=> Use flake8-putty to allow existing flake8 errors

appveyor.yml, cli-options.txt, green/cmdline.py, green/config.py, green/output.py, green/runner.py, green/test/test_cmdline.py, green/test/test_output.py
This PR adds a `-W` or `--nowindows` command line argument that, when present, disables windows support via Colorama.
This is useful for some CI cases, such as GitLab. See  #117.
=> Add CLI option to disable colorama

green/output.py, green/test/test_output.py, green/test/test_windows.py, requirements.txt, setup.py
=> Un-unicode output for Windows CMD

green/result.py, green/test/test_result.py, green/test/test_runner.py
Fixes #123.
This changes the return value and text coloring when no tests are found.
I wasn't able to figure out where any unit tests for this should go (I have limited time today), so if you could let me know where they should go, I'll try writing some tomorrow.
=> "No tests found" now results in a failure.

green/process.py
The `run` function in [runner.py](https://github.com/CleanCut/green/blob/7f4655a/green/runner.py#L117) assumes a specific order of messages from the queue. If the test loader in [`poolRunner`](https://github.com/CleanCut/green/blob/7f4655a/green/process.py#L234) [got an unrunnable object](https://github.com/CleanCut/green/blob/7f4655a/green/process.py#L319), it would attempt to report it, but would never actually put the result in the queue, so the run function would fail because it assumed it would get a result instead of the sentinel `None` from the `cleanup` function.
I think this is because of the changes introduced in [efb54c0](https://github.com/CleanCut/green/commit/efb54c065422d60303b126d694c52bfb8), which moved from putting the result object into the queue in the `stop_callback` …
=> Fix AttributeError when running non-test

green/process.py
Added in [efb54c0](https://github.com/CleanCut/green/commit/efb54c065422d60303b126d694c52bfb8). The test is already put into the queue in the `start_callback`, which filters out this second attempt with the set, but shouldn't need to.
=> Remove duplicate attempt to put test in queue

.travis.yml, test_versions
This expand the Travis test matrix to:
- test Python 3.6 betas and 'nightly' (currently early alpha builts to Python 3.7) as an allowed failure
- move the OSX builds to an 'allowed failure'
=> Travis Matrix

green/config.py, green/result.py, green/test/test_result.py
PR for #148, behaviour is:
- no flag, coverage is not run
- `-r`, coverage is run and coverage report is shown
- `-R`, coverage is run but coverage report is not shown.
=> Add -R flag to run coverage without showing coverage report

green/djangorunner.py, green/test/test_djangorunner.py
* Makes it possible to pass verbosity for Django tests using
command line arguments to `python manage.py test`
* The flag is optional and defaults to `verbose=1`
* The passed value of verbosity overrides value provided in the
.green file or any other configuration file
> Sample usage
> `python manage.py test --green-verbosity 2`
=> [FEATURE] Added --green-verbosity flag for Django test runner

green/config.py, green/test/test_config.py
While I am at it, I added support for green configuration inside `setup.cfg`, since there seem to be [an almost official agreement](http://renesd.blogspot.ch/2017/02/setupcfg-solution-to-python-config-file.html) about using this file for Python dev tools configuration.
`setup.cfg` is the only file where the `[green]` section is expected.
=> Add support for configuration inside 'setup.cfg'

green/cmdline.py, green/djangorunner.py, green/loader.py, green/process.py, green/runner.py, green/test/test_djangorunner.py, green/test/test_load_tests.py, green/test/test_loader.py, green/test/test_runner.py, green/test/test_suite.py
In regards with #87 and #88, I implemented the load_test protocol. To do so, I actually moved functions from `green.loader` to a new class `green.loader.GreenTestLoader`, inheriting from `unittest.TestLoader`.
This way, you can actually use the builtin `unittest.TestLoader.loadTestFromName`, which can run `load_tests` if needed.
Changes are **backwards-incompatible** (although some compatibility patches can be made), as I registered all functions of `green.loader` as methods of `green.loader.GreenTestLoader`.
I also removed `green.loader.loadFromModule` as it was duplicating the `unittest.TestLoader.loadFromModule` code.
I added a test containing a `TestCase` that is expected to fail, but the `load_tests` function in it will
monkey patch the `TestCase` and make the test succeed.
=> Implement GreenTestLoader and load_test protocol

CHANGELOG.md
The past couple version numbers in CHANGELOG.md were incorrect. This fixes them.
=> Fixed version numbers in CHANGELOG.md

README.md, green/cmdline.py, green/command.py, green/config.py, green/test/test_cmdline.py, green/test/test_command.py, green/test/test_djangorunner.py, setup.py
PR for #158.
Allows running green with `python setup.py green` by declaring a distutils command in `green.command`.
The list of arguments is the same as the arguments of the plain green CLI, as it is dynamically generated using the `StoreOpt` results.
I had to change the behaviour of `green.main` a bit, to make it possible to pass it a custom `argv`. The command only validates the input arguments, and then passes everything to `green.main`.
Since distutils commands cannot have positional arguments, I made it possible to specify a test target to use using the `test_suite` argument in the `setup.py`.
=> Implement setup.py runner

green/process.py
Hi Nathan, 
because of a conditional branch the temporary directories that a `poolRunner` call creates are not properly created in Python 3. When running tests several times, the `/tmp` (or equivalent) directory can become cluttered very quickly. I removed the `if` branching so that the temporary folder is always removed.
=> Unconditionally cleanup temp folder in poolRunner

requirements.txt, setup.py
Termstyle has version 0.1.11 instead of 0.1.10.
=> Use termstyle instead of python-termstyle

green/command.py
With the current `green` version installed:
```
python setup.py --help-commands
usage: green [options] [target [target2 ...]]
green: error: unrecognized arguments: --help-commands
```
This is a mistake of mine, as generating the argument list for `green.command.green` actually parses the CLI arguments beforehand, and since it does not know `--help-commands`, the program crashes.
I also changed the description to be more in par with the other tools:
* `behave` description: `Run feature tests with behave`
* `nosetests` description: `Run unit tests using nosetests`
so I changed `green` description to `Run unit tests using green`.
=> Fix `python setup.py --help-commands` not working

README.md
It was difficult to find documentation on green config files, so I copied it to the readme.
=> Copy config files documentation to README

README.md
...not a list. At least for me (Windows 10, Python 3.6.4)
=> setup.py's `test_suite` option must be a string

green/djangorunner.py
Users who see this and copy/paste will receive an error, because the
configuration value in settings.py should be string and therefore enquoted.
Correct this docstring to reflect proper usage.
=> djangorunner: Correct the config declaration.

green/loader.py
Can't be specific about the exception nor contextlib.suppress since python 2 sadly.
Rationale:
I run my tests 1 directory above setup.py and have associated test/runtime data (docker caches) in a misc folder, this would cause green to error and not run.
=> Don't explode on a permissionserror

green/djangorunner.py, green/test/test_djangorunner.py
Fixes the behaviour of Django Test Runner according to the Documentation.
* 'verbosity' is a django thing and is parsed and handled by Django, 'verbose' is the green's labeling, before this fix the only wait to set the 'verbose' configuration while using django was via config file option.
=> Fixed handling of green 'verbose' Django args

green/loader.py, green/test/test_loader.py
In recreating the problem I have found that if there is an import error the 'ModuleImportFailure' gets triggered, and exception_method returns a string that splits at the first space, and if a windows path has a space this causes the bug.
The discover option will go through more directories than unittest, which can possibly try to run tests that weren't expected/wanted, and lead to not knowing where the import error could be caused.
EX:
my project\
|_my_project.py
|
|_tests\
|     |_test_this.py
|
|_side_project\
|            |_fancy_side_project_with_import_error.py
|	     |
|	     |_tests\
|	     	   |_test_side_project.py
when green is run in "my project" the error message will be:
AttributeError: 'ModuleImportFailure' object has no attribute 'my'
My solution is to split on the "(" in …
=> Modified lines 321 and 322 to fix Issue # 176

green/cmdline.py, green/process.py
Run all tests in the dedicated temp dir, which is auto-deleted at the end. The individual test processes create their own temps as subdirectories under this temp dir.
=> Run all tests in the dedicated temp dir

CHANGELOG.md, green/output.py, green/result.py
Time to _finally_ find and fix that annoying "1A" that appears before each result line in AppVeyor and GitHub actions.
=> Fix "1A" appearing at the start of result lines in CI

setup.cfg
When installing `green` in Python 3.10 with `setuptools-62.4.0`, I am getting the following error:
```sh
UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
```
It looks like dashes were deprecated in version 54.1.0 of `setuptools`.
=> Fix UserWarning in setup.cfg

green/loader.py, green/output.py, green/result.py
There are small typos in:
- green/loader.py
- green/output.py
- green/result.py
Fixes:
- Should read `overridden` rather than `overriden`.
- Should read `hierarchies` rather than `heirarchies`.
- Should read `expected` rather than `expeced`.
- Should read `additional` rather than `additonal`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

.github/workflows/ci.yml, green/config.py
=> Fix for Python 3.12

green/config.py, green/result.py
This is new to python 3.12 and throws warning on every single test. This adds the new method and related property. Longer term we should probably inherit from the official TestResult class as to ensure better forward compatibility.
This depends on #274.
=> Address 'addDuration' warnings in python 3.12.

.github/workflows/ci.yml, CHANGELOG.md, Makefile, green/test/test_runner.py, requirements-dev.txt, requirements-optional.txt, requirements.txt, setup.cfg
Improve setup.cfg to perform local dev installs more simply and add a make target that uses vanilla python containers of supported versions for local development.
The new `make test-on-containers` runs under 2m on a M1 Pro machine and runs our tests against python 3.8, 3.9, 3.10, 3.11 and 3.12.0.
=> Improve support for local testing.

green/config.py, green/junit.py, green/loader.py, green/output.py, green/process.py, green/result.py, green/suite.py, green/test/test_command.py, green/test/test_junit.py, green/test/test_load_tests.py, green/test/test_output.py, green/test/test_result.py, green/test/test_runner.py, green/test/test_version.py
This removes code that was here for older versions of python that we no longer support. Unused imports have been removed while missing ones have been added.
=> Cleanup dead code and fix some imports.

.github/workflows/ci.yml, .gitignore, green/loader.py, green/output.py, green/process.py, green/result.py, green/runner.py, green/test/test_result.py, green/test/test_runner.py
This fixes the start time issue with python 3.12.1 but we are still incompatible due to other issues.
In an effort to help debug more this adds more type annotation to the existing code and fix some of the bugs uncovered by mypy.
=> Python 3.12.1 start time

green/cmdline.py, green/command.py, green/config.py, green/djangorunner.py, green/examples.py, green/junit.py, green/process.py, green/result.py, green/suite.py, green/test/test_config.py, green/test/test_junit.py, green/test/test_result.py, green/test/test_runner.py, green/test/test_suite.py
- Improve maintainability of the codebase while leaving the business logic the same.
- Remove more code specific to python 2.7.
- Use sets and tuples instead of lists when they are more efficient.
- Remove redundant `str()` calls.
- Move default_args instantiation to runtime instead of import time.
=> Add more typing to the codebase and minor fixes.

green/config.py, green/djangorunner.py, green/junit.py, green/loader.py, green/output.py, green/process.py, green/result.py, green/runner.py, green/suite.py, green/version.py
This should be the final pass on adding type annotation.
=> Add more typing to the codebase.

.github/workflows/release-test.yml, .github/workflows/release.yml, CHANGELOG.md, release.md
The 'deployment' environments are required to match in the actions.
Validated with the release-test environment which did publish from the action of the official repo.
Once this is merged to main we should be able release 100% from the GH UI.
https://test.pypi.org/project/green/4.0.1/
Released through:
https://github.com/CleanCut/green/actions/runs/7912354962/job/21597969386
```
Checking dist/green-4.0.1.tar.gz: PASSED
Uploading distributions to https://test.pypi.org/legacy/
Uploading green-4.0.1.tar.gz
25l
[ .. snip .. ]
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB • 00:00 • 183.2 MB/s
25h
View at:
https://test.pypi.org/project/green/4.0.1/
```
=> Set environment name for the releases

green/result.py, green/test/test_process.py, green/test/test_result.py
The bug was introduced in commit 651ab467e371b42e6205b9c3d223f2e1f50e4b0a when setting start_time = 0.0 was added to ProtoTestResult.reinitialize().
=> Fix test_time being always 0.0

.github/workflows/ci.yml
Install the project in editable mode, otherwise we run the copy of the code in site-packages which does not match the expected source location.
Closes #289
=> Fix zero coverage in CI

green/cmdline.py, green/config.py, green/runner.py, green/test/test_runner.py
Use forkserver when available to avoid issues with forking multi-threaded processes. See https://github.com/python/cpython/issues/84559 for more context.
This also removes a warning when running on python 3.12 than can be seen in CI:
>/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=1991) is multi-threaded, use of fork() may lead to deadlocks in the child.
>    self.pid = os.fork()
=> Use forkserver start method for multiprocessing

CHANGELOG.md, README-pypi.rst, README.md
This adds a downloads stats badge to the main readme which helps show the popularity of green.
Moved the text around a bit to be consistent with other popular python packages and added the badges to the readme that is published on pypi.org.
=> Add download stats badge.
